// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	Username      string           `db:"username" json:"username"`
	PasswordHash  string           `db:"password_hash" json:"password_hash"`
	Salt          string           `db:"salt" json:"salt"`
	Email         string           `db:"email" json:"email"`
	EmailVerified *bool            `db:"email_verified" json:"email_verified"`
	FirstName     *string          `db:"first_name" json:"first_name"`
	LastName      *string          `db:"last_name" json:"last_name"`
	DateOfBirth   pgtype.Date      `db:"date_of_birth" json:"date_of_birth"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
