services:
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      localhost:8080/api/v1/user/create_user
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "${PORT_API_GATEWAY}:${PORT_API_GATEWAY}"
    networks:
      - backend
    env_file:
      - api-gateway/.env
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - auth

  auth:
    image: auth-service
    container_name: auth-service
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "${PORT_AUTH_SERVICE}:${PORT_AUTH_SERVICE}"
    networks:
      - backend
    env_file:
      - auth/.env
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: qezde-postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: qezde-redis
    restart: unless-stopped
    ports:
      - "${PORT_REDIS}:${PORT_REDIS}"
    volumes:
      - redis-data:/data


networks:
  backend:
    driver: bridge

volumes:
  redis-data:
  postgres-data: