services:
  nextjs:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - BUN_ENV=development
    command: bun --hot run dev
